name: Deploy to Sakura Cloud

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ohgetsu-frontend
      REGISTRY: ohgetsu-frontend.sakuracr.jp
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Rename Dockerfile
        run: mv frontend/production.Dockerfile frontend/Dockerfile

      # tagを取得
      - name: Set tag to environment variables
        id: set-tag
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Sakura Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.SAKURACR_USER }}
          password: ${{ secrets.SAKURACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.version }}
